// 引用元 : https://atcoder.jp/contests/agc012/submissions/10704316
// 得点 : 300
// コード長 : 2736
// 実行時間 : 130


#include <bits/stdc++.h>
#define int long long

#define _overload3(_1,_2,_3,name,...) name
#define _rep(AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA,AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA) repi(AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA,0,AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA)
#define repi(AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA,AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA,AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA) for(int AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=(int)AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA, AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA##_len=(AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA); AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA<AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA##_len; AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA++)
#define rep(...) _overload3(__VA_ARGS__,repi,_rep,)(__VA_ARGS__)

#define all(box) box.begin(), box.end()

using namespace std;

using P = pair<int,int>;
using ll = long long;

const long long INF = LLONG_MAX/3;

template<class T> inline bool chmax(T& AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA, T AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA) { if (AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA < AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA) { AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA = AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA; return 1; } return 0; }
template<class T> inline bool chmin(T& AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA, T AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA) { if (AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA > AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA) { AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA = AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA; return 1; } return 0; }

struct AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA{
	std::vector<int> AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA,AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
	void AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA(int AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA){
		AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.resize(AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA);
		for(int AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=0;AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA<AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA++)AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA[AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA]=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
		AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.resize(AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA,1);
	}
	AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA(int AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA){
		AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA(AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA);
	}
	int AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA(int AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA){
		if(AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA[AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA]==AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA)return AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
		else return AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA[AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA]=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA(AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA[AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA]);
	}
	bool AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA(int AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA,int AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA){
		return (AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA(AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA)==AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA(AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA));
	}
	bool AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA(int AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA,int AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA){
		if(AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA(AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA,AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA))return false;
		else{
			AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA(AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA),AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA(AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA);
			if(AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA[AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA]<AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA[AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA])swap(AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA,AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA);
			AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA[AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA]+=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA[AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA];
			AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA[AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA]=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA[AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA];
			return true;
		}
	}
	int size(int AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA){
		return AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA[AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA(AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA)];
	}
};

long long AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA(long long AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA,long long AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA){
    if(AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==0)return AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
    return AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA(AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA,AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA%AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA);
}
long long lcm(long long AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA,long long AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA){
    return AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA*(AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA(AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA,AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA));
}

const int AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=998244353;
long long AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA[510000], AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA[510000], AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA[510000];
long long AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=510000;
bool AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=false;
long long AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA(int AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA, int AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA){
	if(AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==false){
		AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA[0] = AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA[1] = 1;
    	AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA[0] = AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA[1] = 1;
    	AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA[1] = 1;
    	for (int AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA = 2; AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA < AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA; AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA++){
        	AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA[AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA] = AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA[AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA - 1] * AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA % AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
        	AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA[AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA] = AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA - AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA[AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA%AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA] * (AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA / AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA) % AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
        	AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA[AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA] = AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA[AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA - 1] * AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA[AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA] % AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
    	}
		AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=true;
	}
    if (AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA < AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA) return 0;
    if (AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA < 0 || AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA < 0) return 0;
    return AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA[AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA] * (AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA[AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA] * AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA[AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA - AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA] % AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA) % AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
}
long long AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA(long long AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA, long long AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA, long long AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA) {
    long long AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA = 1;
    while (AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA > 0) {
        if (AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA & 1) AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA = AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA * AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA % AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA = AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA * AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA % AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA >>= 1;
    }
    return AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
}
long long AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA(long long AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA, long long AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA) {
    return AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA(AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA, AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA - 2, AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA);
}
template< typename T >
struct AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA {
  vector< T > AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;

  AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA(int AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA) {
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.assign(++AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA, 0);
  }

  T AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA(int AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA) {
    T AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA = 0;
    for(++AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA; AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA > 0; AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA -= AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA & -AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA) AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA += AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA[AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA];
    return (AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA);
  }

  void AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA(int AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA, T AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA) {
    for(++AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA; AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA < AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.size(); AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA += AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA & -AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA) AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA[AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA] += AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
  }
};
signed main(){
	int AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
	cin>>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
	int AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA[300010];
	rep(AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA,3*AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA)cin>>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA[AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA];
	sort(AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA,AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+3*AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA);
	int AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=0;
	rep(AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA,AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA,3*AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA){
		AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA[AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA];
		AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA++;
	}
	cout<<AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA<<endl;
}
